name: Package
on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      # prepare
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      # install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # build
      - name: Build package
        run: yarn run build

      # lint
      - name: Lint package
        run: yarn run lint

      # test
      - name: Test package
        run: yarn run test

      # publish
      - name: Publish package
        run: yarn publish
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # generate release notes
      - name: Generate release notes
        if: startsWith(github.ref, 'refs/tags/v')
        id: changelog
        run: |
          npx standard-changelog -i /dev/null -o CHANGES.md

      # create github release
      - uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          bodyFile: CHANGES.md
          prerelease: ${{ steps.changelog.outputs.status == 'prereleased' }}
          draft: ${{ steps.changelog.outputs.status == 'unreleased' }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: README.md,LICENSE.md
